# Generated by Django 3.2.25 on 2025-05-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='free_books',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='free_chapters',
        ),
    ]
