# Generated by Django 3.2.25 on 2025-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_remove_free_chapters_free_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
