# Generated by Django 3.2.25 on 2025-05-06 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_ebookstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraping_date', models.DateField(auto_now_add=True, verbose_name='スクレイピング日')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了時間')),
                ('is_success', models.BooleanField(default=False, verbose_name='成功フラグ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_histories', to='manga.ebookstore', verbose_name='電子書籍ストア')),
            ],
            options={
                'verbose_name': 'スクレイピング履歴',
                'verbose_name_plural': 'スクレイピング履歴',
                'ordering': ['-scraping_date', '-started_at'],
                'unique_together': {('store', 'scraping_date')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('free_chapters', models.IntegerField(verbose_name='無料話数')),
                ('free_books', models.IntegerField(verbose_name='無料冊数')),
                ('rank', models.PositiveIntegerField(verbose_name='ランキング順位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scraped_mangas', to='manga.category', verbose_name='カテゴリ')),
                ('scraping_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_mangas', to='manga.scrapinghistory', verbose_name='スクレイピング履歴')),
            ],
            options={
                'verbose_name': 'スクレイピングマンガデータ',
                'verbose_name_plural': 'スクレイピングマンガデータ',
                'ordering': ['scraping_history', 'rank'],
                'unique_together': {('scraping_history', 'title', 'author')},
            },
        ),
    ]
