# Generated by Django 3.2.25 on 2025-05-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='free_books',
            field=models.PositiveIntegerField(default=0, help_text='無料で読める冊数'),
        ),
        migrations.AddField(
            model_name='manga',
            name='free_chapters',
            field=models.PositiveIntegerField(default=0, help_text='無料で読める話数'),
        ),
    ]
