# Generated by Django 3.2.25 on 2025-05-09 08:01

from django.db import migrations


def add_manga_kingdom(apps, schema_editor):
    """まんが王国の電子書籍ストアデータを追加する"""
    EbookStore = apps.get_model('manga', 'EbookStore')
    EbookStore.objects.create(
        name='まんが王国',
        url='https://comic.k-manga.jp/rank/'
    )


def remove_manga_kingdom(apps, schema_editor):
    """まんが王国のデータを削除する（ロールバック用）"""
    EbookStore = apps.get_model('manga', 'EbookStore')
    EbookStore.objects.filter(name='まんが王国').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_scrapedmanga_author'),
    ]

    operations = [
        migrations.RunPython(add_manga_kingdom, remove_manga_kingdom),
    ]
