# Generated by Django 3.2.25 on 2025-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_add_free_chapters_books_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
    ]
