# Generated by Django 3.2.25 on 2025-05-09 08:14

from django.db import migrations


def add_sukima_store(apps, schema_editor):
    """スキマの電子書籍ストアデータを追加する"""
    EbookStore = apps.get_model('manga', 'EbookStore')
    EbookStore.objects.create(
        name='スキマ',
        url='https://www.sukima.me/book/ranking/?genre=GENERAL&term=MONTHLY&type=BESTSELLER'
    )


def remove_sukima_store(apps, schema_editor):
    """スキマのデータを削除する（ロールバック用）"""
    EbookStore = apps.get_model('manga', 'EbookStore')
    EbookStore.objects.filter(name='スキマ').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_add_manga_kingdom_store'),
    ]

    operations = [
        migrations.RunPython(add_sukima_store, remove_sukima_store),
    ]
