# Generated by Django 3.2.25 on 2025-06-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_add_isbn_to_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='first_book_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1巻タイトル'),
        ),
    ]
