# Generated by Django 3.2.25 on 2025-06-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_add_first_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaEbookStoreDetailUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='詳細URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('ebookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_detail_urls', to='manga.ebookstore', verbose_name='電子書籍ストア')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_detail_urls', to='manga.manga', verbose_name='マンガ')),
            ],
            options={
                'verbose_name': '電子書籍ストア別マンガ詳細URL',
                'verbose_name_plural': '電子書籍ストア別マンガ詳細URL',
                'db_table': 'manga_manga_ebookstore_detaiurl',
                'ordering': ['manga', 'ebookstore'],
                'unique_together': {('manga', 'ebookstore')},
            },
        ),
    ]
