# Generated by Django 3.2.25 on 2025-06-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_mangaebookstoredetailurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MangaEbookStoreDetailUrl',
            new_name='MangaEbookStore',
        ),
        migrations.AlterModelTable(
            name='mangaebookstore',
            table='manga_manga_ebookstore',
        ),
    ]
