# Generated by Django 3.2.25 on 2025-06-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_auto_20250618_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaebookstore',
            name='free_books',
            field=models.IntegerField(default=0, verbose_name='無料巻数'),
        ),
        migrations.AddField(
            model_name='mangaebookstore',
            name='free_chapters',
            field=models.IntegerField(default=0, verbose_name='無料話数'),
        ),
    ]
