# Generated by Django 3.2.25 on 2025-05-09 09:06

from django.db import migrations


def migrate_existing_urls(apps, schema_editor):
    """
    既存の電子書籍ストアのURLを「全て」カテゴリのURLとして新しいテーブルに移行
    """
    EbookStore = apps.get_model('manga', 'EbookStore')
    EbookStoreCategoryUrl = apps.get_model('manga', 'EbookStoreCategoryUrl')
    Category = apps.get_model('manga', 'Category')
    
    # 「全て」カテゴリを取得（なければ作成）
    all_category, created = Category.objects.get_or_create(
        id='all',
        defaults={'name': '全て'}
    )
    
    # 各ストアのURLを移行
    for store in EbookStore.objects.all():
        # 既に同じストアとカテゴリの組み合わせがある場合はスキップ
        if not EbookStoreCategoryUrl.objects.filter(store=store, category=all_category).exists():
            EbookStoreCategoryUrl.objects.create(
                store=store,
                category=all_category,
                url=store.url  # 既存のURLを「全て」カテゴリとして設定
            )


def reverse_migrate_urls(apps, schema_editor):
    """
    マイグレーションの巻き戻し処理（何もしない）
    既存のEbookStoreのURLは維持されているので特に操作不要
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_auto_20250509_1805'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_urls, reverse_migrate_urls),
    ]
