version: '3.8'

services:
  api:
    build: .
    command: sh -c "python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=mysql://root:password@db:3306/free_manga_db
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=free_manga_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  scraper:
    build: .
    command: sh -c "python -m debugpy --listen 0.0.0.0:5679 --wait-for-client manage.py runscript test_scraper --script-args=\"ebookstore_e\""
    volumes:
      - .:/code
    ports:
      - "5679:5679"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  mysql_data: