# Generated by Django 3.2.25 on 2025-05-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(choices=[('all', '全て'), ('shounen', '少年マンガ'), ('shoujo', '少女マンガ'), ('seinen', '青年マンガ'), ('josei', '女性マンガ')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('cover_image', models.URLField()),
                ('free_chapters', models.IntegerField()),
                ('free_books', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='manga.category')),
            ],
            options={
                'verbose_name': 'マンガ',
                'verbose_name_plural': 'マンガ',
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
