# Generated by Django 3.2.25 on 2025-05-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_add_sukima_store'),
    ]

    operations = [
    ]
