# Generated by Django 3.2.25 on 2025-05-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_add_ebookstore_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookstore',
            name='url',
            field=models.URLField(help_text='この値は下位互換性のために残されています。新しいカテゴリURLはEbookStoreCategoryUrlを使用してください。', verbose_name='スクレイピング対象URL (総合カテゴリ)'),
        ),
        migrations.CreateModel(
            name='EbookStoreCategoryUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='スクレイピング対象URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_urls', to='manga.category', verbose_name='カテゴリ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_urls', to='manga.ebookstore', verbose_name='電子書籍ストア')),
            ],
            options={
                'verbose_name': 'ストアカテゴリURL',
                'verbose_name_plural': 'ストアカテゴリURL',
                'ordering': ['store', 'category'],
                'unique_together': {('store', 'category')},
            },
        ),
    ]
