# Generated by Django 3.2.25 on 2025-05-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_migrate_store_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='category',
        ),
        migrations.AddField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(related_name='mangas', to='manga.Category', verbose_name='カテゴリ'),
        ),
    ]
