# Generated by Django 3.2.25 on 2025-05-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_auto_20250510_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedmanga',
            name='manga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='scraped_mangas', to='manga.manga', verbose_name='マンガ'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scrapedmanga',
            unique_together={('scraping_history', 'manga')},
        ),
        migrations.RemoveField(
            model_name='scrapedmanga',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scrapedmanga',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scrapedmanga',
            name='title',
        ),
    ]
