# Generated by Django 3.2 on 2025-05-10
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('manga', '0011_auto_20250510_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='int_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
