# Generated by Django 3.2.25 on 2025-05-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_manga_id_bigautofield'),
        ('manga', '0013_set_int_id'),
    ]

    operations = [
    ]
