# Generated by Django 3.2 on 2025-05-10
from django.db import migrations

def overwrite_id_with_int_id(apps, schema_editor):
    Manga = apps.get_model('manga', 'Manga')
    for manga in Manga.objects.all():
        if manga.int_id is not None:
            manga.id = manga.int_id
            manga.save(update_fields=['id'])

class Migration(migrations.Migration):
    dependencies = [
        ('manga', '0014_merge_0013_manga_id_bigautofield_0013_set_int_id'),
    ]

    operations = [
        migrations.RunPython(overwrite_id_with_int_id),
    ]
