# Generated by Django 3.2.25 on 2025-05-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_manga_id_bigautofield'),
        ('manga', '0015_overwrite_id_with_int_id'),
    ]

    operations = [
    ]
