# Generated by Django 3.2.25 on 2025-05-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_merge_20250510_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='int_id',
        ),
    ]
