# Generated by Django (manual) on 2025-05-10
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('manga', '0017_remove_manga_int_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_chapters', models.IntegerField(verbose_name='無料話数')),
                ('free_books', models.IntegerField(verbose_name='無料冊数')),
                ('rank', models.PositiveIntegerField(verbose_name='ランキング順位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('scraping_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_mangas', to='manga.scrapinghistory', verbose_name='スクレイピング履歴')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scraped_mangas', to='manga.manga', verbose_name='マンガ')),
            ],
            options={
                'verbose_name': 'スクレイピングマンガデータ',
                'verbose_name_plural': 'スクレイピングマンガデータ',
                'ordering': ['scraping_history', 'rank'],
                'unique_together': {('scraping_history', 'manga')},
            },
        ),
    ]
